# This is duplicated here from configs/mydoc/config_designers.yml so that Github Pages can read it. Github Pages requires this file for the build process. It can't read a configuration file stored in another location.

# project definitions
project: mydoc_designers
audience: designers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/mydoc/designers
topnav_title: AgileSafe
homepage_title: AgileSafe
site_title: AgileSafe
project_folder: mydoc
company_name: Katarzyna Łukasiewicz
footer_image_location: ../common_images/company_logo.png
github_editme_path:
#disqus_shortname: idrbwjekyll
# variables

sidebar_tagline: AgileSafe
sidebar_version:  safety friendly agile approach
theme_file: theme-blue.css
pdf_file_name: mydoc_designers_pdf.pdf

port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: katarzyna.lukasiewicz@pg.gda.pl

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: false
      search: true
      tooltip: true

